# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.dingo.com:
  peer0.client1.dingo.com:
  peer1.client1.dingo.com:
  peer0.client2.dingo.com:
  peer1.client2.dingo.com:

networks:
  net_dingo:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-client1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.client1.dingo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.client1.dingo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/client1.dingo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerClient1
    networks:
      - net_dingo

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-client2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.client2.dingo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.client2.dingo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/client2.dingo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerClient2
    networks:
      - net_dingo

  orderer.dingo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.dingo.com
    container_name: orderer.dingo.com
    networks:
      - net_dingo

  peer0.client1.dingo.com:
    container_name: peer0.client1.dingo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.client1.dingo.com
    networks:
      - net_dingo

  peer1.client1.dingo.com:
    container_name: peer1.client1.dingo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.client1.dingo.com
    networks:
      - net_dingo

  peer0.client2.dingo.com:
    container_name: peer0.client2.dingo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.client2.dingo.com
    networks:
      - net_dingo

  peer1.client2.dingo.com:
    container_name: peer1.client2.dingo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.client2.dingo.com
    networks:
      - net_dingo
